#！/usr/bin/python
#-*-coding:utf-8-*-
#···
#编写人：郑晓璇
#编写时间：20181018
#实现功能：用turtle库绘制奥运五环

import turtle as t 
t.color("blue")
t.pensize(10) 
t.penup() 
t.goto(-110,-25)  
t.pendown() 
t.circle(45)
t.color("black")
t.pensize(10) 
t.penup()
t.goto(0,-25)
t.pendown()
t.circle(45)
t.color("red")
t.pensize(10) 
t.penup()
t.goto(110,-25)
t.pendown()
t.circle(45)
t.color("yellow")
t.pensize(10) 
t.penup()
t.goto(-55,-75)
t.pendown()
t.circle(45)
t.color("green")
t.pensize(10) 
t.penup()
t.goto(55,-75)
t.pendown()
t.circle(45)
input()
